'use client';
import { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

export default function ReportViewer() {
  const [report, setReport] = useState<string | null>(null);
  const [stats, setStats] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    setReport(null);
    try {
      const res = await fetch('/api/reports');
      const data = await res.json();
      if (data.error) {
        setError(data.error);
      } else {
        setReport(data.report);
        setStats(data.stats);
      }
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <Card className="p-6">
      <h2 className="text-xl font-medium mb-2">AI-Generated Reports</h2>
      <p className="text-sm text-muted-foreground mb-4">
        Claude analyzes the past 7 days of donation activity and writes a
        professional report for stakeholders.
      </p>

      <Button onClick={generate} disabled={loading}>
        {loading ? 'Claude is writing...' : 'Generate Weekly Report'}
      </Button>

      {error && (
        <div className="mt-4 p-3 rounded bg-red-50 border border-red-200 text-red-800 text-sm">
          ✗ {error}
        </div>
      )}

      {stats && (
        <div className="mt-6 grid grid-cols-2 md:grid-cols-4 gap-3">
          <StatBox label="Donations received" value={stats.totalDonations} />
          <StatBox label="Items distributed" value={stats.totalDistributed} />
          <StatBox label="Beneficiaries served" value={stats.beneficiariesServed} />
          <StatBox label="Categories at risk" value={stats.shortages.length} />
        </div>
      )}

      {stats && stats.topCategories.length > 0 && (
        <div className="mt-4 flex flex-wrap gap-2 items-center">
          <span className="text-sm text-muted-foreground">Top categories:</span>
          {stats.topCategories.map((c: any) => (
            <Badge key={c.name} variant="secondary">
              {c.name} ({c.count})
            </Badge>
          ))}
        </div>
      )}

      {report && (
        <div className="mt-6 p-5 border rounded-lg bg-white">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-xs uppercase tracking-wide text-muted-foreground">
              Generated by Claude
            </span>
          </div>
          <div className="prose prose-sm max-w-none whitespace-pre-wrap leading-relaxed">
            {report}
          </div>
        </div>
      )}
    </Card>
  );
}

function StatBox({ label, value }: { label: string; value: number }) {
  return (
    <div className="p-3 rounded-lg border bg-white">
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="text-2xl font-medium mt-1">{value}</p>
    </div>
  );
}
