export type Locale = 'en' | 'zh' | 'es';

export const SUPPORTED_LOCALES: Locale[] = ['en', 'zh', 'es'];

export function detectBrowserLocale(): Locale {
  if (typeof window === 'undefined') return 'en';
  const lang = navigator.language || navigator.languages?.[0] || 'en';
  const code = lang.toLowerCase().split('-')[0];
  if (code === 'zh') return 'zh';
  if (code === 'es') return 'es';
  return 'en';
}

export const LOCALE_LABELS: Record<Locale, string> = {
  en: '🇺🇸 EN',
  zh: '🇨🇳 中文',
  es: '🇲🇽 ES',
};

export const LOCALE_INSTRUCTION: Record<Locale, string> = {
  en: 'Respond entirely in English.',
  zh: '请完全用中文回答，包括所有标签、说明和建议。',
  es: 'Responde completamente en español, incluyendo todas las etiquetas, explicaciones y recomendaciones.',
};

export const UI = {
  en: {
    appSubtitle: "Smart donation management for women's centers",
    tabIntake: 'Intake', tabInventory: 'Inventory', tabDistribute: 'Distribute', tabReports: 'Reports',
    intakeTitle: 'Add Donation (Natural Language)',
    intakePlaceholder: 'e.g. got 3 boxes of canned food, 2 winter coats size L, 10 cans of baby formula...',
    intakeParseBtn: 'Parse with AI', intakeParsing: 'Parsing...', intakeParsedItems: 'Parsed items:',
    intakeSaveBtn: 'Confirm & Save', intakeSaving: 'Saving...',
    reportTitle: 'AI-Generated Reports',
    reportSubtitle: 'Claude analyzes the past 7 days of donation activity and writes a professional report for stakeholders.',
    reportGenerateBtn: 'Generate Weekly Report', reportGenerating: 'Claude is writing...',
    reportDonationsReceived: 'Donations received', reportItemsDistributed: 'Items distributed',
    reportBeneficiariesServed: 'Beneficiaries served', reportCategoriesAtRisk: 'Categories at risk',
    reportTopCategories: 'Top categories:', reportGeneratedBy: 'Generated by Claude',
  },
  zh: {
    appSubtitle: '妇女中心智能捐赠管理系统',
    tabIntake: '捐赠录入', tabInventory: '库存', tabDistribute: '分配', tabReports: '报告',
    intakeTitle: '添加捐赠（自然语言）',
    intakePlaceholder: '例如：收到3箱罐头食品、2件L码冬季外套、10罐婴儿奶粉...',
    intakeParseBtn: 'AI 解析', intakeParsing: '解析中...', intakeParsedItems: '解析结果：',
    intakeSaveBtn: '确认并保存', intakeSaving: '保存中...',
    reportTitle: 'AI 生成报告',
    reportSubtitle: 'Claude 分析过去7天的捐赠活动，为相关人员生成专业报告。',
    reportGenerateBtn: '生成周报', reportGenerating: 'Claude 正在撰写...',
    reportDonationsReceived: '已接收捐赠', reportItemsDistributed: '已分发物资',
    reportBeneficiariesServed: '服务受益人', reportCategoriesAtRisk: '短缺类别',
    reportTopCategories: '热门类别：', reportGeneratedBy: '由 Claude 生成',
  },
  es: {
    appSubtitle: 'Gestión inteligente de donaciones para centros de mujeres',
    tabIntake: 'Ingreso', tabInventory: 'Inventario', tabDistribute: 'Distribuir', tabReports: 'Informes',
    intakeTitle: 'Agregar Donación (Lenguaje Natural)',
    intakePlaceholder: 'ej. recibí 3 cajas de comida enlatada, 2 abrigos talla L, 10 latas de fórmula...',
    intakeParseBtn: 'Analizar con IA', intakeParsing: 'Analizando...', intakeParsedItems: 'Artículos detectados:',
    intakeSaveBtn: 'Confirmar y Guardar', intakeSaving: 'Guardando...',
    reportTitle: 'Informes Generados por IA',
    reportSubtitle: 'Claude analiza los últimos 7 días de actividad de donaciones y genera un informe profesional.',
    reportGenerateBtn: 'Generar Informe Semanal', reportGenerating: 'Claude está escribiendo...',
    reportDonationsReceived: 'Donaciones recibidas', reportItemsDistributed: 'Artículos distribuidos',
    reportBeneficiariesServed: 'Beneficiarios atendidos', reportCategoriesAtRisk: 'Categorías en riesgo',
    reportTopCategories: 'Categorías principales:', reportGeneratedBy: 'Generado por Claude',
  },
} as const;
